services:
  client:
    build: ./client
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: ./server
    ports:
      - 5434:5434
    environment:
      MONGO_URI: mongodb://db/simpleoj
      PORT: 5434
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - redis:redis

  # db:
  #   image: mongo:4.0-xenial
  #   ports:
  #     - 27018:27017
  #   volumes:
  #     - simpleoj:/data/db

  redis:
    image: redis:alpine3.16

volumes:
  simpleoj:
