services:
  server:
    build: .
    ports:
      - 5434:5434
    volumes:
      - ./:/app
      - /app/node_modules
    links:
      - redis:redis

  redis:
    image: redis:alpine3.16

volumes:
  simpleoj:
